# Generated by Django 3.1.4 on 2020-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturelist',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lecturelist',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
